# Generated by Django 6.0.5 on 2026-05-11 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happydentApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='happydentApi.staff')),
                ('shift_type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'nurse',
                'managed': False,
            },
        ),
    ]
