# Generated by Django 6.0.5 on 2026-05-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happydentApi', '0006_patientrecordview_patientsearchview_vstaffsalary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VPatientAppointments',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('staff_id', models.CharField(max_length=10)),
                ('patient_id', models.CharField(max_length=10)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('doctor_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'v_patient_appointments',
                'managed': False,
            },
        ),
    ]
