# Generated by Django 6.0.5 on 2026-05-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happydentApi', '0008_patientbillingview'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDueRecord',
            fields=[
                ('record_id', models.IntegerField(primary_key=True, serialize=False)),
                ('patient_id', models.CharField(max_length=20)),
                ('visit_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'patient_due_records',
                'managed': False,
            },
        ),
    ]
