# Generated by Django 6.0.5 on 2026-05-15 17:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happydentApi', '0012_managementfulldetailsview'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientFullDetailsView',
            fields=[
                ('patient_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=120)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('has_diabetes', models.BooleanField(blank=True, null=True)),
                ('has_hypertension', models.BooleanField(blank=True, null=True)),
                ('has_allergies', models.BooleanField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('phone_numbers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'patient_full_details_view',
                'managed': False,
            },
        ),
    ]
