# Generated by Django 6.0.5 on 2026-05-16 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happydentApi', '0014_departmentstaffsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierFullDetailsView',
            fields=[
                ('supplier_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'supplier_full_details_view',
                'managed': False,
            },
        ),
    ]
