# Generated by Django 6.0.5 on 2026-05-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happydentApi', '0016_administrativebudgetview_companybudgetsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierDropdownView',
            fields=[
                ('supplier_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'supplier_dropdown_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('item_id', models.TextField(primary_key=True, serialize=False)),
                ('item_name', models.TextField()),
                ('category', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('unit', models.TextField(blank=True, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('supplier_id', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Inventory',
            },
        ),
    ]
