# Generated by Django 6.0.5 on 2026-05-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happydentApi', '0002_nurse'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(blank=True, max_length=10, null=True)),
                ('name_first', models.CharField(blank=True, max_length=50, null=True)),
                ('name_last', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('availability', models.BooleanField(blank=True, null=True)),
                ('dept_name', models.CharField(blank=True, max_length=100, null=True)),
                ('qualifications', models.TextField(blank=True, null=True)),
                ('specializations', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'doctor_directory',
                'managed': False,
            },
        ),
    ]
