# Generated by Django 6.0.5 on 2026-05-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happydentApi', '0003_doctordirectory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedAppointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=10)),
                ('patient_id', models.CharField(max_length=10)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
            ],
            options={
                'db_table': 'accepted_appointments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PendingAppointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=10)),
                ('patient_id', models.CharField(max_length=10)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
            ],
            options={
                'db_table': 'pending_appointments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RejectedAppointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=10)),
                ('patient_id', models.CharField(max_length=10)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
            ],
            options={
                'db_table': 'rejected_appointments',
                'managed': False,
            },
        ),
    ]
