# Generated by Django 6.0.5 on 2026-05-14 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happydentApi', '0004_acceptedappointments_pendingappointments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordClinicalNotes',
            fields=[
                ('pk', models.CompositePrimaryKey('record_id', 'clinical_notes', blank=True, editable=False, primary_key=True, serialize=False)),
                ('clinical_notes', models.TextField()),
            ],
            options={
                'db_table': 'record_clinical_notes',
                'managed': False,
            },
        ),
    ]
