# Generated by Django 6.0.5 on 2026-05-14 14:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happydentApi', '0005_recordclinicalnotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRecordView',
            fields=[
                ('record_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('patient_id', models.CharField(blank=True, max_length=10, null=True)),
                ('name_first', models.CharField(blank=True, max_length=50, null=True)),
                ('name_last', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('phones', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list)),
                ('treatment_plan', models.TextField(blank=True, null=True)),
                ('prescription', models.TextField(blank=True, null=True)),
                ('procedure_done', models.CharField(blank=True, max_length=255, null=True)),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('next_appointment', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('staff_id', models.CharField(blank=True, max_length=10, null=True)),
                ('clinical_notes', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list)),
            ],
            options={
                'db_table': 'patient_record_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PatientSearchView',
            fields=[
                ('patient_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('name_first', models.CharField(blank=True, max_length=50, null=True)),
                ('name_last', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('phones', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list)),
            ],
            options={
                'db_table': 'patient_search_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VStaffSalary',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('staff_id', models.CharField(max_length=10)),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bonus', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('deduction', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('net_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'v_staff_salary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VStaffSalarySummary',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('staff_id', models.CharField(max_length=10)),
                ('total_base_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_bonus', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_deduction', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_net_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'v_staff_salary_summary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VStaffSalaryYearly',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('staff_id', models.CharField(max_length=10)),
                ('year', models.DateField()),
                ('total_base_salary', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('total_bonus', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('total_deduction', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('total_net_salary', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'v_staff_salary_yearly',
                'managed': False,
            },
        ),
    ]
