# Generated by Django 6.0.5 on 2026-05-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happydentApi', '0007_vpatientappointments'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientBillingView',
            fields=[
                ('bill_id', models.IntegerField(primary_key=True, serialize=False)),
                ('record_id', models.IntegerField()),
                ('patient_id', models.CharField(max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(max_length=50)),
                ('visit_date', models.DateField()),
                ('staff_id', models.CharField(max_length=20)),
                ('appointment_with', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'patient_billing_view',
                'managed': False,
            },
        ),
    ]
