# Generated by Django 6.0.5 on 2026-05-15 11:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happydentApi', '0009_patientduerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorFullDetailsView',
            fields=[
                ('staff_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=201)),
                ('gender', models.CharField(max_length=20)),
                ('staff_role', models.CharField(max_length=50)),
                ('dept_id', models.CharField(max_length=10)),
                ('phone_numbers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list)),
                ('qualifications', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list)),
                ('specializations', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list)),
            ],
            options={
                'db_table': 'doctor_full_details_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PatientPaymentSummary',
            fields=[
                ('patient_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('total_bill_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount_due', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'patient_payment_summary',
                'managed': False,
            },
        ),
    ]
