# Generated by Django 6.0.5 on 2026-05-15 13:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happydentApi', '0010_doctorfulldetailsview_patientpaymentsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseFullDetailsView',
            fields=[
                ('staff_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=201)),
                ('gender', models.CharField(max_length=20)),
                ('staff_role', models.CharField(max_length=50)),
                ('dept_id', models.CharField(max_length=10)),
                ('acc_status', models.CharField(max_length=20)),
                ('shift_type', models.CharField(max_length=20)),
                ('phone_numbers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list)),
            ],
            options={
                'db_table': 'nurse_full_details_view',
                'managed': False,
            },
        ),
    ]
