# Generated by Django 6.0.5 on 2026-05-15 15:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happydentApi', '0011_nursefulldetailsview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementFullDetailsView',
            fields=[
                ('staff_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=201)),
                ('gender', models.CharField(max_length=20)),
                ('staff_role', models.CharField(max_length=50)),
                ('dept_id', models.CharField(max_length=10)),
                ('acc_status', models.CharField(max_length=20)),
                ('clearance_level', models.CharField(blank=True, max_length=20, null=True)),
                ('budget_authority', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('budget_used', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('phone_numbers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list)),
            ],
            options={
                'db_table': 'management_full_details_view',
                'managed': False,
            },
        ),
    ]
