# Generated by Django 6.0.5 on 2026-05-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happydentApi', '0013_patientfulldetailsview'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentStaffSummary',
            fields=[
                ('dept_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=100)),
                ('room_number', models.BigIntegerField(null=True)),
                ('total_staff', models.IntegerField()),
            ],
            options={
                'db_table': 'department_staff_summary',
                'managed': False,
            },
        ),
    ]
