# Generated by Django 6.0.5 on 2026-05-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happydentApi', '0015_supplierfulldetailsview'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeBudgetView',
            fields=[
                ('staff_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('clearance_level', models.CharField(max_length=20)),
                ('budget_authority', models.DecimalField(decimal_places=2, max_digits=15)),
                ('budget_used', models.DecimalField(decimal_places=2, max_digits=15)),
                ('budget_remaining', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'administrative_budget_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyBudgetSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_budget_authority', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_budget_used', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_budget_remaining', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'company_budget_summary',
                'managed': False,
            },
        ),
    ]
